version: "3.3"

services:
  ms_vehicles-tes: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms_notifications-test
    env_file:
      - ./variables.env
    ports:
      - "6000:6000"
      - "5674:5674"
    command: npm start
    networks:
      - ucar-network
    volumes:
      - /home/ucar-admin/secrets/serviceAccountKey.json:/usr/src/app/serviceAccountKey.json:ro


networks:
  ucar-network:
    external: true
 